apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aid.fullname" . }}-config
  labels:
    {{- include "aid.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.config.DEBUG | quote }}
  ALLOWED_HOSTS: {{ .Values.config.ALLOWED_HOSTS | quote }}
  CSRF_TRUSTED_ORIGINS: {{ .Values.config.CSRF_TRUSTED_ORIGINS | quote }}
