# Generated by Django 6.0.6 on 2026-06-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField()),
                ('trabajador', models.CharField(choices=[('Manu', 'Manu'), ('Jorge', 'Jorge'), ('Babi', 'Babi'), ('Nico', 'Nico')], max_length=20)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=12)),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('salida', models.TimeField(blank=True, null=True)),
                ('bruto', models.FloatField(default=0, editable=False)),
                ('neto', models.FloatField(default=0, editable=False)),
                ('extra', models.FloatField(default=0, editable=False)),
                ('es_libre', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['semana_inicio', 'trabajador', 'dia'],
                'unique_together': {('semana_inicio', 'trabajador', 'dia')},
            },
        ),
    ]
