# Generated by Django 6.0.6 on 2026-06-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('contenido', models.TextField(blank=True)),
                ('formato', models.CharField(choices=[('md', 'Markdown'), ('txt', 'Texto plano')], default='md', max_length=3)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-actualizado', '-id'],
            },
        ),
    ]
